# general configuration
version: '{branch}.{build}'

# environment configuration
image: Visual Studio 2017
clone_folder: C:\projects\rdkafka
environment:
  BIN_SDK_VER: 2.2.0
  DEP: librdkafka-1.5.3
  matrix:
    - PHP_VER: 8.1
      TS: 0
      VC: vs16
      ARCH: x64
      OPCACHE: 0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PHP_VER: 8.1
      TS: 1
      VC: vs16
      ARCH: x64
      OPCACHE: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PHP_VER: 8.2
      TS: 0
      VC: vs16
      ARCH: x64
      OPCACHE: 0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PHP_VER: 8.2
      TS: 1
      VC: vs16
      ARCH: x64
      OPCACHE: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PHP_VER: 8.3
      TS: 0
      VC: vs16
      ARCH: x64
      OPCACHE: 0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PHP_VER: 8.3
      TS: 1
      VC: vs16
      ARCH: x64
      OPCACHE: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

cache:
  - C:\build-cache -> .appveyor.yml, .appveyor\install.ps1
install:
  - ps: .appveyor\install.ps1

# build configuration
build_script:
  - ps: .appveyor\build.ps1

after_build:
  - ps: .appveyor\package.ps1
