name: 'Package'

on:
    pull_request:

jobs:
    package:
        name: 'Package'
        runs-on: 'ubuntu-24.04'
        steps:
            - name: 'Check out repository'
              uses: 'actions/checkout@v2'
              with:
                  path: 'php-rdkafka'

            - name: 'Install dependencies'
              run: 'sudo apt-get -y install php-dev librdkafka-dev'

            - name: 'Package and verify package'
              run: './php-rdkafka/.github/workflows/package/package.sh'

            - name: 'Archive package'
              uses: 'actions/upload-artifact@v4'
              with:
                  path: 'php-rdkafka/rdkafka.tgz'
